### ISSUE TITLE
capa de falla

### ISSUE THREAD

**Issue by rgarcia-herrera** [sostenibilidad-unam/abm2#1]

**Comment by rgarcia-herrera** [comment]
edad de infraestructura

**Comment by edithvilla** [comment]
Criterio **Falla** (en Infraestructura) se define: # Fallas de infraestructura hidráulica ocasionadas por conexiones clandestinas, obstrucción por basura y procesos biofísicos.

**Comment by marcoajh** [comment]
Pueden usarse como proxy las franjas de crecimiento urbano, la infraestructura central será mas vieja que la periférica.

**Comment by marcoajh** [comment]
Verificar si hay mejor información.

**Comment by marcoajh** [comment]
Capa dummy hecha, se sigue trabajando en la capa con datos reales, ver repositorio planeacion-colaborativa
