### ISSUE TITLE
capa de calidad de agua

### ISSUE THREAD

**Issue by rgarcia-herrera** [sostenibilidad-unam/abm2#10]

**Comment by edithvilla** [comment]
Criterio **Calidad de agua** (en Riesgos población) se define: # Riesgo a la salud por la mala calidad del agua, ejemplos: epidemias y contaminación bioquímica.

**Comment by marcoajh** [comment]
No tenemos información cartográfica de este criterio, quizá en Arizona tengan algún proxy

**Comment by marcoajh** [comment]
@edithvilla solicitará información a Ana Cecilia Espinoza

**Comment by marcoajh** [comment]
Capa dummy hecha, se sigue trabajando en la capa con datos reales, ver repositorio planeacion-colaborativa
