### ISSUE TITLE
capa de escasez de agua

### ISSUE THREAD

**Issue by rgarcia-herrera** [sostenibilidad-unam/abm2#11]

**Comment by edithvilla** [comment]
Criterio **Escasez de agua** (en Riesgos población) se define: # Cantidad de agua insuficiente para ls necesidades diarias (derecho humano) (por volumen u horas de entrega).

**Comment by marcoajh** [comment]
Tenemos información de tandeo por colonia, podríamos normalizar los datos y re-clasificar cada AGEB.  Quizá en Arizona tengan un mejor proxy

**Comment by marcoajh** [comment]
Tabla que relacione AGEB-Colonia, con los datos de tandeo.

**Comment by marcoajh** [comment]
Capa dummy hecha, se sigue trabajando en la capa con datos reales, ver repositorio planeacion-colaborativa
