### ISSUE TITLE
capa de presión hidráulica

### ISSUE THREAD

**Issue by rgarcia-herrera** [sostenibilidad-unam/abm2#12]

**Comment by edithvilla** [comment]
Criterio **Presión hidráulica** (en Infraestructura) se define: # Presión del agua en las tuberías (litros por segundo). Peso:

**Comment by marcoajh** [comment]
No tenemos información cartográfica de este criterio, quizá en Arizona tengan algún proxy

**Comment by marcoajh** [comment]
Capa dummy hecha, se sigue trabajando en la capa con datos reales, ver repositorio planeacion-colaborativa
