### ISSUE TITLE
capa de capacidad de abastecimiento

### ISSUE THREAD

**Issue by rgarcia-herrera** [sostenibilidad-unam/abm2#13]

**Comment by edithvilla** [comment]
Criterio **Capacidad** (en Infraestructura) se define: ## Capacidad de la infraestructura hidráulica. Peso: 

Criterio **Abastecimiento** (en Socio-institucional) se define: ## Necesidad de la población en cuanto a servicios hidráulicos (agua potable, drenaje). Peso:

**Comment by marcoajh** [comment]
Para **Capacidad** puede usarse la capa de la red primaria de abastecimiento, a mayor cantidad de tuberías mayor capacidad.
Para **Almacenamiento** puede usarse la población total de cada AGEB multiplicada algún factor estándar de consumo de agua

**Comment by marcoajh** [comment]
Para Capacidad. Crear una tabla con éstos campos: población AGEB, superficie AGEB m2, metros de tubería AGEB  y superficie urbana en el AGEB
Para Abastecimiento. Crear tabla con los siguientes campos: Número de viviendas totales, Número de viviendas sin agua potable, Población total AGEB

**Comment by marcoajh** [comment]
Las tablas son: 
Capacidad.ods y Abastecimiento.ods 
En 
132.247.90.93/MEGADAPT_integracion/CarpetasTrabajo/Marco/sub_criterios_ABM/

**Comment by marcoajh** [comment]
Capa dummy hecha, se sigue trabajando en la capa con datos reales, ver repositorio planeacion-colaborativa
