### ISSUE TITLE
capa de temperatura

### ISSUE THREAD

**Issue by rgarcia-herrera** [sostenibilidad-unam/abm2#3]

**Comment by edithvilla** [comment]
Yosune

**Comment by marcoajh** [comment]
Pueden usarse los datos de WRF, también tenemos una capa de temperatura del proyecto de Cuenca del Valle de México, aunque no es la misma extensión.

**Comment by yosunemiquela** [comment]
Según lo que había entendido era la capa proporcionada por Vivoni y Kristen cierto?

La capa de temperatura y precipitación de WRF que tenemos es la georeferenciada...

**Comment by marcoajh** [comment]
La capa no es necesaria dentro del modelo
