### ISSUE TITLE
capa de subsidencia

### ISSUE THREAD

**Issue by rgarcia-herrera** [sostenibilidad-unam/abm2#4]

**Comment by edithvilla** [comment]
Criterio **Subsidencia** (en Biofísico) se define: # Hundimiento diferenciales.

**Comment by marcoajh** [comment]
Hay una capa de hundimientos, pero sólo se indica el proceso por el cual se da el hundimiento y no la magnitud.

**Comment by marcoajh** [comment]
Mostrar capa de subsidencia

**Comment by marcoajh** [comment]
Capa dummy hecha, se sigue trabajando en la capa con datos reales, ver repositorio planeacion-colaborativa
