### ISSUE TITLE
capa de falta de infraestructura

### ISSUE THREAD

**Issue by rgarcia-herrera** [sostenibilidad-unam/abm2#5]
Se refiere a infraestructura de distribución de agua.

**Comment by edithvilla** [comment]
Criterio **Falta** (en Infraestructura) se define: # Falta de infraestructura hidráulica.

**Comment by marcoajh** [comment]
Puede usarse una función inversa a partir de la capa de la red primaria de abastecimiento, sería lo opuesto al criterio **Capacidad**. Podría ser binaria, donde hay y no hay infraestructura.

**Comment by marcoajh** [comment]
Tabla de distancias a red primaria y porcentaje de área urbana en cada anillo de ditancia. 
tabla de población y superficie en cada AGEB

**Comment by marcoajh** [comment]
Capa dummy hecha, se sigue trabajando en la capa con datos reales, ver repositorio planeacion-colaborativa
