### ISSUE TITLE
capa de uso de suelo

### ISSUE THREAD

**Issue by rgarcia-herrera** [sostenibilidad-unam/abm2#6]

**Comment by edithvilla** [comment]
Criterio **Cambio de uso de suelo** (en Biofísico) se define:#  Cambio de uso de suelo que afecta la calidad de agua e incrementa la demanda de infraestructura y servicios.

**Comment by marcoajh** [comment]
¿Cambio de uso habitacional a uso comercial? Todas las AGEB están catalogadas como uso urbano. No tenemos capa de cambio de uso de suelo habitacional a comercial o industrial o de servicios, quizá Sergio Flores y su equipo si posean ésta información

**Comment by marcoajh** [comment]
Tabla de cambio Serie III a Serie V por AGEB
(precisar años de cada serie)
Lista de categoría para hacer la reclasificación para el jueves 26

**Comment by marcoajh** [comment]
La capa serie III corresponde al año 2002
La capa serie V corresponde al año 2011
La tabla se llama:
uso_de_suelo.xlsx
En:
132.247.90.93/MEGADAPT_integracion/CarpetasTrabajo/Marco/sub_criterios_ABM/

**Comment by paola-gp** [comment]
Listo, ahora hacer cruza

**Comment by marcoajh** [comment]
Re-clasificación actualizada de las series II y V
Ya está lista la cruza de datos, el archivo es:
/132.247.90.93/MEGADAPT_integracion/CarpetasTrabajo/Marco/sub_criterios_ABM/AGEB_Cobertura.csv
En espera del Vo.Bo de @PaolaGomezPriego

**Comment by paola-gp** [comment]
gracias
