### ISSUE TITLE
capa de protestas

### ISSUE THREAD

**Issue by rgarcia-herrera** [sostenibilidad-unam/abm2#7]
capa inicial

**Comment by edithvilla** [comment]
En el modelo multicriterio no existe el criterio Protestas

Criterio **Presión social** (en Socio-institucional) se define: # Percepción del descontento social directa de la población e indirecta a través de agencias de gobierno, quejas, comentarios recibidos por redes sociales y teléfonos.

**Comment by marcoajh** [comment]
No tenemos información cartográfica de este criterio, quizá en Arizona tengan algún proxy

**Comment by marcoajh** [comment]
Capa dummy hecha, se sigue trabajando en la capa con datos reales, ver repositorio planeacion-colaborativa
