### ISSUE TITLE
capa de petición delegacional

### ISSUE THREAD

**Issue by rgarcia-herrera** [sostenibilidad-unam/abm2#8]

**Comment by edithvilla** [comment]
Criterio **Petición de Delegaciones** (en Socio-institucional) se define: # Solicitud de servicios e infraestructura hidráulica o nuevas conexiones al sistema hidráulico por Delegaciones.

**Comment by marcoajh** [comment]
No tenemos información cartográfica de este criterio, quizá en Arizona tengan algún proxy

**Comment by marcoajh** [comment]
Crear cuenta en Infomex y verificar pesos @edithvilla

**Comment by marcoajh** [comment]
No es relevante

**Comment by marcoajh** [comment]
Capa dummy hecha, se sigue trabajando en la capa con datos reales, ver repositorio planeacion-colaborativa
