### ISSUE TITLE
capa de infiltración

### ISSUE THREAD

**Issue by rgarcia-herrera** [sostenibilidad-unam/abm2#9]

**Comment by edithvilla** [comment]
Criterio **Infiltración** (en Biofísico) se define: # Tasa de infiltración de los escurrimientos en la recarga de agua de los mantos acuíferos.

**Comment by marcoajh** [comment]
Pueden usarse las capas de infiltración de Mooser y área urbana para re-clasificar cada AGEB

**Comment by marcoajh** [comment]
Tabla con los siguientes campos: área urbana, categoría de Mooser, área del AGEB,, ID AGEB

**Comment by marcoajh** [comment]
La tabla es:
Infiltración.ods
en
132.247.90.93/MEGADAPT_integracion/CarpetasTrabajo/Marco/sub_criterios_ABM/

**Comment by marcoajh** [comment]
Capa dummy hecha, se sigue trabajando en la capa con datos reales, ver repositorio planeacion-colaborativa
